;;;; MarMUD mapper attributes

{:name "MarMUD mapper system"
 :base :vr/mapper
 :area-list [:okaga/bridge
             :okaga/galley
             :okaga/immersim
             :okaga/library
             :okaga/passageways
             :teraum/eastlands/central-plains/east-kingsroad
             :teraum/eastlands/central-plains/fort-kelly
             :teraum/eastlands/central-plains/west-kingsroad-1
             :teraum/eastlands/central-plains/west-kingsroad-2
             :teraum/eastlands/cut/central-oasis
             :teraum/eastlands/cut/eastern-canyons
             :teraum/eastlands/cut/southern-canyons
             :teraum/eastlands/farsteppes/castle-oru
             :teraum/eastlands/farsteppes/culver-estate
             :teraum/eastlands/farsteppes/helmets-dent
             :teraum/eastlands/farsteppes/road-to-culver-estate
             :teraum/eastlands/gloaming/central-longroad
             :teraum/eastlands/gloaming/north-longroad
             :teraum/eastlands/gloaming/road-to-jacobs-folly
             :teraum/eastlands/gloaming/south-longroad
             :teraum/eastlands/gloaming/belcaer/chandlers-guild-office
             :teraum/eastlands/gloaming/belcaer/lobby
             :teraum/eastlands/gloaming/belcaer/offices
             :teraum/eastlands/gloaming/jacobs-folly/outside
             :teraum/eastlands/green-delta/arathel-county/first-church-of-povator
             :teraum/eastlands/green-delta/arathel-county/kaiper-river
             :teraum/eastlands/green-delta/arathel-county/old-arathel
             :teraum/eastlands/green-delta/arathel-county/reinhard-lumberworks
             :teraum/eastlands/green-delta/arathel-county/second-church-of-povator
             :teraum/eastlands/green-delta/arathel-county/siggrit-temple
             :teraum/eastlands/green-delta/game/kingsroad
             :teraum/eastlands/green-delta/game/widdershins-road
             :teraum/eastlands/green-delta/game/ack/angers-place
             :teraum/eastlands/green-delta/game/ack/astar-ward
             :teraum/eastlands/green-delta/game/ack/bank-hill
             :teraum/eastlands/green-delta/game/ack/carper-falls
             :teraum/eastlands/green-delta/game/ack/copper-ward
             :teraum/eastlands/green-delta/game/ack/east-gate
             :teraum/eastlands/green-delta/game/ack/garys-gate
             :teraum/eastlands/green-delta/game/ack/gasper
             :teraum/eastlands/green-delta/game/ack/north-ward
             :teraum/eastlands/green-delta/game/ack/piketown-gate
             :teraum/eastlands/green-delta/game/ack/piketown
             :teraum/eastlands/green-delta/game/ack/poplar-gate
             :teraum/eastlands/green-delta/game/ack/red-ward
             :teraum/eastlands/green-delta/game/ack/reinhard-wood
             :teraum/eastlands/green-delta/game/ack/squash-ward
             :teraum/eastlands/green-delta/game/ack/sugar-heights
             :teraum/eastlands/green-delta/game/ack/the-dog
             :teraum/eastlands/green-delta/game/ack/tin-ward
             :teraum/eastlands/green-delta/game/ack/wineglass
             :teraum/eastlands/green-delta/game/ack/brass-ward/kingsroad
             :teraum/eastlands/green-delta/game/ack/brass-ward/caliper-street/street
             
             :teraum/eastlands/green-delta/game/ack/brass-ward/caliper-street/114
             :teraum/eastlands/green-delta/game/ack/dock-ward/main
             :teraum/eastlands/green-delta/game/ack/dock-ward/harbour
             :teraum/eastlands/green-delta/game/bellybrush/arathel-road
             :teraum/eastlands/green-delta/game/bellybrush/east-harbrook-street
             :teraum/eastlands/green-delta/game/bellybrush/east-kingsroad
             :teraum/eastlands/green-delta/game/bellybrush/forth-and-wahl
             :teraum/eastlands/green-delta/game/bellybrush/kingsroad-outside-orphanage
             :teraum/eastlands/green-delta/game/bellybrush/west-harbrook-street
             :teraum/eastlands/green-delta/game/bellybrush/west-kingsroad
             :teraum/eastlands/green-delta/game/bellybrush/westgate
             :teraum/eastlands/green-delta/game/south-arathel/bellybrush-road
             :teraum/eastlands/green-delta/game/south-arathel/belys-blades
             :teraum/eastlands/green-delta/game/south-arathel/broken-arrow-inn
             :teraum/eastlands/green-delta/game/south-arathel/crossed-candles-inn
             :teraum/eastlands/green-delta/game/south-arathel/dull-thorn-inn-quarters
             :teraum/eastlands/green-delta/game/south-arathel/dull-thorn-inn
             :teraum/eastlands/green-delta/game/south-arathel/fork-toward-honeyfern-labs
             :teraum/eastlands/green-delta/game/south-arathel/golden-shield-inn
             :teraum/eastlands/green-delta/game/south-arathel/north-arathel-ack-road
             :teraum/eastlands/green-delta/game/south-arathel/outside-broken-arrow-inn
             :teraum/eastlands/green-delta/game/south-arathel/outside-dull-thorn-inn
             :teraum/eastlands/green-delta/game/south-arathel/outside-golden-shield-inn
             :teraum/eastlands/green-delta/game/south-arathel/road-near-frekes-grave
             :teraum/eastlands/green-delta/game/south-arathel/road-to-honeyfern-labs
             :teraum/eastlands/green-delta/game/south-arathel/south-arathel-ack-road
             :teraum/eastlands/green-delta/game/south-arathel/turnwise-road
             :teraum/eastlands/green-delta/game/south-arathel/west-arathel-pled-road
             :teraum/eastlands/green-delta/game/south-arathel/honeyfern-labs/dining-hall
             :teraum/eastlands/green-delta/game/south-arathel/honeyfern-labs/first-floor-hallway
             :teraum/eastlands/green-delta/game/south-arathel/honeyfern-labs/foyer
             :teraum/eastlands/green-delta/game/south-arathel/honeyfern-labs/front-path
             :teraum/eastlands/green-delta/game/south-arathel/honeyfern-labs/front-porch
             :teraum/eastlands/green-delta/game/south-arathel/honeyfern-labs/kitchen
             :teraum/eastlands/green-delta/game/south-arathel/honeyfern-labs/library
             :teraum/eastlands/green-delta/game/south-arathel/honeyfern-labs/outside-gate
             :teraum/eastlands/green-delta/game/south-arathel/honeyfern-labs/pantry
             :teraum/eastlands/green-delta/game/south-arathel/honeyfern-labs/sitting-room
             :teraum/eastlands/green-delta/marby-county/eridrin
             :teraum/eastlands/green-delta/pled-county/daughts-cottage
             :teraum/eastlands/green-delta/pled-county/west-arathel-pled-road
             :teraum/eastlands/green-delta/sherwyn-county/chauntean-monastery
             ]
 :start-area :okaga/bridge}
